### ISSUE TITLE
When user try Translate message and facing Crash issue

### ISSUE THREAD

**Issue by Nivs113** [cometchat-pro/android-java-chat-ui-kit#2]
### When user try to Translate/Edit message and facing Crash issue

> java.lang.ClassCastException: com.cometchat.pro.uikit.ui_components.messages.message_list.CometChatMessageListActivity cannot be cast to com.cometchat.pro.uikit.ui_components.messages.thread_message_list.CometChatThreadMessageListActivity
        at com.cometchat.pro.uikit.ui_components.messages.message_actions.CometChatMessageActions.onDismiss(CometChatMessageActions.java:365)
        at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:253)
        at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:222)
        at com.google.android.material.bottomsheet.BottomSheetDialogFragment.dismiss(BottomSheetDialogFragment.java:47)
        at com.cometchat.pro.uikit.ui_components.messages.message_actions.CometChatMessageActions$5.onClick(CometChatMessageActions.java:263)
        at android.view.View.performClick(View.java:7161)
        at android.view.View.performClickInternal(View.java:7133)
        at android.view.View.access$3500(View.java:804)
        at android.view.View$PerformClick.run(View.java:27416)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:7617)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

**Comment by Nivs113** [comment]
@darshanbhanushali  can you please solve this. and provide a update in sdk

**Comment by darshanbhanushali** [comment]
Hi,

We checked at our end and it's working fine, can you please check whether you have added `composeBox.usedIn()` in [`CometChatMessageList`](https://github.com/cometchat-pro/android-java-chat-ui-kit/blob/master/uikit/src/main/java/com/cometchat/pro/uikit/ui_components/messages/message_list/CometChatMessageList.java#L354) & [`CometChatThreadMessageList`](https://github.com/cometchat-pro/android-java-chat-ui-kit/blob/master/uikit/src/main/java/com/cometchat/pro/uikit/ui_components/messages/thread_message_list/CometChatThreadMessageList.java#L583) 
Also please check [CometChatMessageActions](https://github.com/cometchat-pro/android-java-chat-ui-kit/blob/master/uikit/src/main/java/com/cometchat/pro/uikit/ui_components/messages/message_actions/CometChatMessageActions.java#L358).

**Comment by Nivs113** [comment]
@darshanbhanushali Yes sir, it's added already and this is only facing on live build, in while development it's working fine.

**Comment by darshanbhanushali** [comment]
Hi,

We checked at our end in released build and it's working fine. The above issue occurs only if you have missed `composeBox.usedIn()` in CometChatMessageList. 
We will suggest you to please check [`CometChatMessageList`](https://github.com/cometchat-pro/android-java-chat-ui-kit/blob/master/uikit/src/main/java/com/cometchat/pro/uikit/ui_components/messages/message_list/CometChatMessageList.java#L354) , [`CometChatThreadMessageList`](https://github.com/cometchat-pro/android-java-chat-ui-kit/blob/master/uikit/src/main/java/com/cometchat/pro/uikit/ui_components/messages/thread_message_list/CometChatThreadMessageList.java#L583) and [`CometChatMessageActions`](https://github.com/cometchat-pro/android-java-chat-ui-kit/blob/master/uikit/src/main/java/com/cometchat/pro/uikit/ui_components/messages/message_actions/CometChatMessageActions.java#L358).

Also if you have added something in build.gradle file then please share with us.

**Comment by paarthsabharwal** [comment]
Hi @Nivs113 ,
I hope this was of help.
I am closing this thread out due to inactivity.

Feel free to reach out to us here or email us at help@cometchat.com for technical assistance.
We will be happy to help.
