### ISSUE TITLE
Crash app while chossing file in chatting screen on android 11

### ISSUE THREAD

**Issue by Nivs113** [cometchat-pro/android-java-chat-ui-kit#3]
### Fatal Exception: java.lang.RuntimeException  

> Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65561, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/document:14584 flg=0x43 }} to activity {com.cometchat.pro.uikit.ui_components.messages.message_list.CometChatMessageListActivity}: java.lang.NullPointerException: uri
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5475)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5516)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2295)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

### Caused by java.lang.NullPointerException uri
> Caused by java.lang.NullPointerException: uri
       at java.util.Objects.requireNonNull(Objects.java:245)
       at android.content.ContentResolver.query(ContentResolver.java:1160)
       at android.content.ContentResolver.query(ContentResolver.java:1118)
       at android.content.ContentResolver.query(ContentResolver.java:1074)
       at com.cometchat.pro.uikit.ui_resources.utils.MediaUtils.getDataColumn(MediaUtils.java:576)
       at com.cometchat.pro.uikit.ui_resources.utils.MediaUtils.getRealPathFromURI_API19(MediaUtils.java:513)
       at com.cometchat.pro.uikit.ui_resources.utils.MediaUtils.getRealPath(MediaUtils.java:317)
       at com.cometchat.pro.uikit.ui_components.messages.message_list.CometChatMessageList.onActivityResult(CometChatMessageList.java:1389)
       at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:170)
       at com.cometchat.pro.uikit.ui_components.messages.message_list.CometChatMessageListActivity.onActivityResult(CometChatMessageListActivity.java:97)
       at android.app.Activity.dispatchActivityResult(Activity.java:8526)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5468)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5516)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2295)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by Nivs113** [comment]
@darshanbhanushali , can you look into this, this issue happened in Android 11(R), while choosing file from storage in chat. 
Device Information : 
Device : Samsung A51
Android Version : 11(R)

**Comment by subdee** [comment]
This happens also on Android 9. When you select a file to upload, the app crashes. Some debugging shows that no Attachment object is created for the BaseMessage, and so it crashes.

**Comment by darshanbhanushali** [comment]
Hi,

We will suggest you to please check with the latest UI Kit. As we have added a new method _getFilePathForN()_ which has fixed this issue.

You can check the below link for reference.
https://github.com/cometchat-pro/android-java-chat-ui-kit/blob/master/uikit/src/main/java/com/cometchat/pro/uikit/ui_resources/utils/MediaUtils.java#L313-L331

**Comment by proveshapyne** [comment]
Hello @Nivs113, @subdee,

Hope upgrading to the latest UI kit version helped resolve your issues.
Feel free to create another ticket or reach out to help@cometchat.com for more technical help.

Regards,
Provesha
